# Site settings
title: Editorial Technology
email: me@maetl.net
description: "Software made to measure"
baseurl: ""
url: "http://editorial.technology"
twitter_username: EditorialTech
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty


